language: cpp
sudo: false
matrix:
  include:
    - os: osx
      compiler: clang

git:
  depth: 5

before_install:
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install swig sdl2 sdl2_image sdl2_ttf freetype openal-soft tinyxml glew libvorbis python3; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then virtualenv env -p python3; source env/bin/activate; fi

install:
  - git clone --quiet --depth 1 git://github.com/fifengine/fifechan.git
  - if [ $TRAVIS_OS_NAME == osx ]; then mkdir build_fifechan; cd build_fifechan; cmake ../fifechan; fi
  - make -j3
  - sudo make install
  - cd ..

script:
  - git clone --quiet --depth 1 git://github.com/fifengine/fifechan.git
  - if [ $TRAVIS_OS_NAME == osx ]; then mkdir build_fifechan; cd build_fifechan; cmake ../fifechan; fi
  - make -j3
  - sudo make install
  - cd ..

script:
  - cd ..
  - if [ $TRAVIS_OS_NAME == osx ]; then mkdir build; cd build; cmake -DPYTHON_EXECUTABLE:PATH=/usr/local/bin/python3 -DPYTHON_LIBRARY=/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/ ../fifengine; fi #-DPYTHON_SITE_PACKAGES=/usr/local/Cellar/fifengine/lib/python3.6/site-packages
  - ls -alh .
  - make -j3
  - sudo make install

after_script: 
  - cd $TRAVIS_BUILD_DIR
  - python3 -c 'from fife import fife; print(fife.getVersion())'

notifications:
  irc: irc.freenode.org#fife
  email: false
