language: cpp
sudo: false
matrix:
  include:
    - os: osx
      compiler: clang
      python: "3.6"

git:
  depth: 5

before_install:
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install swig sdl2 sdl2_image sdl2_ttf freetype openal-soft tinyxml glew libvorbis python3; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then virtualenv env -p python3; source env/bin/activate; fi
  - cmake --version

install:
    #- git clone --quiet --depth 1 git://github.com/fifengine/fifechan.git
    # https://github.com/fifengine/fifechan/blob/master/INSTALL.md
    #- if [ $TRAVIS_OS_NAME == osx ]; then mkdir build_fifechan; cd build_fifechan; cmake ../fifechan; fi
    #- make -j3
   # - sudo make install
   # - cd ..

script:
   - cd ..
   - cd /usr/local/Cellar/python3
   - ls
   - cd /usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/include/python3.6m/
   - ls
   - cd /usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib
   - ls
   - if [ $TRAVIS_OS_NAME == osx ]; then mkdir build; cd build; cmake -DPYTHON_EXECUTABLE:PATH=/usr/local/bin/python3 -DPYTHON_INCLUDE_DIR=/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/include/python3.6m/ -DPYTHON_LIBRARY=/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/ ../fifengine; fi
   - ls -alh .
   - make -j3
   - sudo make install

after_script: 
   - cd /home/travis/build/fifengine/fifengine
   - if [ $TRAVIS_OS_NAME == linux ]; then cppcheck --verbose --enable=all --std=posix --std=c++11 --quiet -iengine/core/ext engine/core; fi
   - if [ $TRAVIS_OS_NAME == linux ]; then pylint --rcfile=.pylintrc ./engine/python/fife/; fi

notifications:
  irc: irc.freenode.org#fife
  email: false

#deploy:
#  provider: releases
#  api_key:
#    secure: "TiE1MLzq8DE2vJjiTeWnuhjEM/cH4hQ7yL/SSDkIqTijCY1eiCX6KPE7yDNh9F1SkCfxYyDPTuRc+f1EaAbk073aL56kUTM/bV/4TEcHk4TS40Hcd5aA10gR3XOH3lYwagT2edgXgXLA1cvU1tuwj8stKz1hEnkVlCvFdbvy4qg="
#  file: Fifengine*.tar.gz
#  file_glob: true
#  skip_cleanup: true
#  overwrite: true
#  on:
#    tags: true
